/**
 * AI Financial Insights — AI-powered analysis of cooperative financial data.
 *
 * Provides:
 * - P&L summaries with natural language explanations
 * - Savings analysis with growth recommendations
 * - Loan performance insights
 * - Risk assessments
 * - Dividend projections
 *
 * All insights are generated by the AI using real data.
 */

import { prisma } from "./prisma.js";
import { getCoopSnapshot, getSavingsTrend, getLoanPerformance } from "./ai-data.js";
import { groqFetch, groqAvailable, groqModel, GROQ_TIMEOUT_MS } from "./groq.js";

/**
 * Generate AI-powered financial insights.
 */
export async function generateFinancialInsights(
  cooperativeId: string,
): Promise<string> {
  if (!groqAvailable()) {
    return generateFallbackInsights(cooperativeId);
  }

  const [snapshot, trends, performance] = await Promise.all([
    getCoopSnapshot(cooperativeId),
    getSavingsTrend(cooperativeId, 6),
    getLoanPerformance(cooperativeId),
  ]);

  const data = { snapshot, trends, performance };

  try {
    const res = await groqFetch({
      model: groqModel(),
      temperature: 0.3,
      max_tokens: 500,
      messages: [
        {
          role: "system",
          content: `You are a financial analyst for a Nigerian cooperative.
Generate concise, actionable insights from the provided data.
Do not invent numbers. Only use data provided.
Focus on:
1. Financial health assessment
2. Savings trends and growth
3. Loan performance and risks
4. Recommendations for improvement

Note: These are AI-generated observations, not financial advice.
Use the format: ₦XX,XXX for amounts. Be specific with numbers.
Keep it under 300 words. Be professional but warm.`,
        },
        {
          role: "user",
          content: `Generate financial insights for this cooperative:\n\n${JSON.stringify(data, null, 2)}`,
        },
      ],
    }, GROQ_TIMEOUT_MS);

    if (!res.ok) return generateFallbackInsights(cooperativeId);
    const body = (await res.json()) as {
      choices?: Array<{ message?: { content?: string } }>;
    };
    const raw = body.choices?.[0]?.message?.content ?? generateFallbackInsights(cooperativeId);
    return raw + "\n\n_Disclaimer: This is an AI-generated analysis and may not be fully accurate. Contact your cooperative admin for official information._";
  } catch {
    return generateFallbackInsights(cooperativeId);
  }
}

/**
 * Generate fallback insights when AI is unavailable.
 */
async function generateFallbackInsights(cooperativeId: string): Promise<string> {
  const [snapshot, trends, performance] = await Promise.all([
    getCoopSnapshot(cooperativeId),
    getSavingsTrend(cooperativeId, 6),
    getLoanPerformance(cooperativeId),
  ]);

  const fmt = (n: number) => `₦${(n / 100).toLocaleString()}`;

  let insights = `📊 *Cooperative Financial Insights*\n\n`;

  // Financial Health
  insights += `*Financial Health:*\n`;
  insights += `• Total savings: ${fmt(snapshot.finances.totalSaved)}\n`;
  insights += `• Wallet balance: ${fmt(snapshot.finances.totalWalletBalance)}\n`;
  insights += `• Active loan balance: ${fmt(snapshot.finances.activeLoanBalance)}\n\n`;

  // Savings Trend
  insights += `*Savings Trend (6 months):*\n`;
  const recentTrends = trends.slice(-3);
  recentTrends.forEach((t) => {
    insights += `• ${t.month}: ${fmt(t.amount)}\n`;
  });
  insights += `\n`;

  // Loan Performance
  insights += `*Loan Performance:*\n`;
  insights += `• Repayment rate: ${performance.repaymentRate.toFixed(1)}%\n`;
  insights += `• Total loans: ${performance.totalLoans}\n`;
  insights += `• Repaid: ${performance.paidLoans}\n`;
  if (performance.defaultedLoans > 0) {
    insights += `• ⚠️ Defaulted: ${performance.defaultedLoans}\n`;
  }
  insights += `\n`;

  // Key Metrics
  insights += `*Key Metrics:*\n`;
  insights += `• Members: ${snapshot.cooperative.activeMemberCount}\n`;
  insights += `• Pending withdrawals: ${snapshot.finances.pendingWithdrawals}\n`;
  insights += `• Daily payout limit: ${fmt(snapshot.finances.dailyPayoutLimit)}\n`;

  return insights;
}

/**
 * Generate loan risk assessment for the cooperative.
 * Admin-only: exposes overdue member names which are PII.
 */
export async function generateLoanRiskAssessment(
  cooperativeId: string,
  role?: string,
): Promise<string> {
  if (role !== "admin" && role !== "superadmin") {
    return "⚠️ Loan risk assessment is only available to cooperative admins.";
  }

  const [performance, overdueLoans] = await Promise.all([
    getLoanPerformance(cooperativeId),
    prisma.loan.findMany({
      where: {
        cooperativeId,
        status: "disbursed",
        dueDate: { lt: new Date() },
      },
      include: { member: true },
    }),
  ]);

  const fmt = (n: number) => `₦${(n / 100).toLocaleString()}`;

  let assessment = `⚠️ *Loan Risk Assessment*\n\n`;

  // Overall risk
  const riskLevel =
    performance.repaymentRate > 80 ? "Low" :
    performance.repaymentRate > 60 ? "Medium" : "High";

  assessment += `Risk Level: *${riskLevel}*\n`;
  assessment += `Repayment Rate: ${performance.repaymentRate.toFixed(1)}%\n\n`;

  // Overdue loans
  if (overdueLoans.length > 0) {
    assessment += `*Overdue Loans (${overdueLoans.length}):*\n`;
    overdueLoans.forEach((loan) => {
      const daysOverdue = Math.ceil(
        (Date.now() - loan.dueDate!.getTime()) / (24 * 60 * 60 * 1000),
      );
      assessment += `• ${loan.member.name}: ${fmt(loan.balance)} (${daysOverdue} days)\n`;
    });
    assessment += `\n`;
  }

  // Recommendations
  assessment += `*Recommendations:*\n`;
  if (overdueLoans.length > 0) {
    assessment += `• Follow up on ${overdueLoans.length} overdue loan(s).\n`;
  }
  if (performance.repaymentRate < 70) {
    assessment += `• Consider tightening loan approval criteria.\n`;
  }
  if (performance.repaymentRate > 90) {
    assessment += `• Excellent repayment rate! Consider expanding loan offerings.\n`;
  }

  return assessment;
}
