/**
 * AI Financial Insights — AI-powered analysis of cooperative financial data.
 *
 * Provides:
 * - P&L summaries with natural language explanations
 * - Savings analysis with growth recommendations
 * - Loan performance insights
 * - Risk assessments
 * - Dividend projections
 *
 * All insights are generated by the AI using real data.
 */

import { prisma } from "./prisma.js";
import { formatBalance } from "../services/cooperative.js";
import { getCoopSnapshot, getSavingsTrend, getLoanPerformance } from "./ai-data.js";

const GROQ_URL = "https://api.groq.com/openai/v1/chat/completions";

/**
 * Generate AI-powered financial insights.
 */
export async function generateFinancialInsights(
  cooperativeId: string,
): Promise<string> {
  if (!process.env.GROQ_API_KEY) {
    return generateFallbackInsights(cooperativeId);
  }

  const [snapshot, trends, performance] = await Promise.all([
    getCoopSnapshot(cooperativeId),
    getSavingsTrend(cooperativeId, 6),
    getLoanPerformance(cooperativeId),
  ]);

  const data = { snapshot, trends, performance };

  try {
    const res = await fetch(GROQ_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${process.env.GROQ_API_KEY}`,
      },
      body: JSON.stringify({
        model: process.env.GROQ_MODEL || "llama-3.1-8b-instant",
        temperature: 0.3,
        max_tokens: 500,
        messages: [
          {
            role: "system",
            content: `You are a financial analyst for a Nigerian cooperative.
Generate concise, actionable insights from the provided data.
Focus on:
1. Financial health assessment
2. Savings trends and growth
3. Loan performance and risks
4. Recommendations for improvement

Use the format: ₦XX,XXX for amounts. Be specific with numbers.
Keep it under 300 words. Be professional but warm.`,
          },
          {
            role: "user",
            content: `Generate financial insights for this cooperative:\n\n${JSON.stringify(data, null, 2)}`,
          },
        ],
      }),
      signal: AbortSignal.timeout(10000),
    });

    if (!res.ok) return generateFallbackInsights(cooperativeId);
    const body = (await res.json()) as {
      choices?: Array<{ message?: { content?: string } }>;
    };
    return body.choices?.[0]?.message?.content ?? generateFallbackInsights(cooperativeId);
  } catch {
    return generateFallbackInsights(cooperativeId);
  }
}

/**
 * Generate fallback insights when AI is unavailable.
 */
async function generateFallbackInsights(cooperativeId: string): Promise<string> {
  const [snapshot, trends, performance] = await Promise.all([
    getCoopSnapshot(cooperativeId),
    getSavingsTrend(cooperativeId, 6),
    getLoanPerformance(cooperativeId),
  ]);

  const fmt = (n: number) => `₦${(n / 100).toLocaleString()}`;

  let insights = `📊 *Cooperative Financial Insights*\n\n`;

  // Financial Health
  insights += `*Financial Health:*\n`;
  insights += `• Total savings: ${fmt(snapshot.finances.totalSaved)}\n`;
  insights += `• Wallet balance: ${fmt(snapshot.finances.totalWalletBalance)}\n`;
  insights += `• Active loan balance: ${fmt(snapshot.finances.activeLoanBalance)}\n\n`;

  // Savings Trend
  insights += `*Savings Trend (6 months):*\n`;
  const recentTrends = trends.slice(-3);
  recentTrends.forEach((t) => {
    insights += `• ${t.month}: ${fmt(t.amount)}\n`;
  });
  insights += `\n`;

  // Loan Performance
  insights += `*Loan Performance:*\n`;
  insights += `• Repayment rate: ${performance.repaymentRate.toFixed(1)}%\n`;
  insights += `• Total loans: ${performance.totalLoans}\n`;
  insights += `• Repaid: ${performance.paidLoans}\n`;
  if (performance.defaultedLoans > 0) {
    insights += `• ⚠️ Defaulted: ${performance.defaultedLoans}\n`;
  }
  insights += `\n`;

  // Key Metrics
  insights += `*Key Metrics:*\n`;
  insights += `• Members: ${snapshot.cooperative.activeMemberCount}\n`;
  insights += `• Pending withdrawals: ${snapshot.finances.pendingWithdrawals}\n`;
  insights += `• Daily payout limit: ${fmt(snapshot.finances.dailyPayoutLimit)}\n`;

  return insights;
}

/**
 * Generate savings analysis for a member.
 */
export async function generateSavingsAnalysis(
  memberId: string,
  cooperativeId: string,
): Promise<string> {
  const [member, trends] = await Promise.all([
    prisma.member.findUnique({
      where: { id: memberId },
      include: { wallet: true },
    }),
    getSavingsTrend(cooperativeId, 6),
  ]);

  if (!member?.wallet) return "Could not load your savings data.";

  const fmt = (n: number) => `₦${(n / 100).toLocaleString()}`;

  let analysis = `📊 *Your Savings Analysis*\n\n`;
  analysis += `Current balance: ${fmt(member.wallet.balance)}\n`;
  analysis += `Total saved: ${fmt(member.wallet.totalSaved)}\n\n`;

  // Personal trend
  const memberTrends = await prisma.contribution.groupBy({
    by: ["createdAt"],
    where: {
      memberId,
      status: "confirmed",
    },
    _sum: { amount: true },
    orderBy: { createdAt: "desc" },
    take: 6,
  });

  if (memberTrends.length > 1) {
    const first = memberTrends[memberTrends.length - 1]?._sum.amount ?? 0;
    const last = memberTrends[0]?._sum.amount ?? 0;
    if (first > 0) {
      const growth = ((last - first) / first) * 100;
      analysis += `Growth: ${growth > 0 ? "+" : ""}${growth.toFixed(1)}%\n`;
    }
  }

  // Recommendations
  analysis += `\n*Recommendations:*\n`;
  if (member.wallet.balance < 100000) {
    analysis += `• Consider increasing your monthly savings to build your emergency fund.\n`;
  }
  if (member.wallet.totalSaved > 500000) {
    analysis += `• Great savings! You may be eligible for a loan.\n`;
  }

  return analysis;
}

/**
 * Generate loan risk assessment for the cooperative.
 */
export async function generateLoanRiskAssessment(
  cooperativeId: string,
): Promise<string> {
  const [performance, overdueLoans] = await Promise.all([
    getLoanPerformance(cooperativeId),
    prisma.loan.findMany({
      where: {
        cooperativeId,
        status: "disbursed",
        dueDate: { lt: new Date() },
      },
      include: { member: true },
    }),
  ]);

  const fmt = (n: number) => `₦${(n / 100).toLocaleString()}`;

  let assessment = `⚠️ *Loan Risk Assessment*\n\n`;

  // Overall risk
  const riskLevel =
    performance.repaymentRate > 80 ? "Low" :
    performance.repaymentRate > 60 ? "Medium" : "High";

  assessment += `Risk Level: *${riskLevel}*\n`;
  assessment += `Repayment Rate: ${performance.repaymentRate.toFixed(1)}%\n\n`;

  // Overdue loans
  if (overdueLoans.length > 0) {
    assessment += `*Overdue Loans (${overdueLoans.length}):*\n`;
    overdueLoans.forEach((loan) => {
      const daysOverdue = Math.ceil(
        (Date.now() - loan.dueDate!.getTime()) / (24 * 60 * 60 * 1000),
      );
      assessment += `• ${loan.member.name}: ${fmt(loan.balance)} (${daysOverdue} days)\n`;
    });
    assessment += `\n`;
  }

  // Recommendations
  assessment += `*Recommendations:*\n`;
  if (overdueLoans.length > 0) {
    assessment += `• Follow up on ${overdueLoans.length} overdue loan(s).\n`;
  }
  if (performance.repaymentRate < 70) {
    assessment += `• Consider tightening loan approval criteria.\n`;
  }
  if (performance.repaymentRate > 90) {
    assessment += `• Excellent repayment rate! Consider expanding loan offerings.\n`;
  }

  return assessment;
}
